// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef OI_H
#define OI_H
#include "WPILib.h"
class OI {
private:
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Joystick* operatorJoystick;
    JoystickButton* operator_Xbox_RJoy;
    JoystickButton* operator_Xbox_LJoy;
    JoystickButton* operator_Xbox_Start;
    JoystickButton* operator_Xbox_Select;
    JoystickButton* operator_Xbox_Y;
    JoystickButton* operator_Xbox_X;
    JoystickButton* operator_Xbox_B;
    JoystickButton* operator_Xbox_A;
    JoystickButton* operator_Xbox_RightBumper;
    JoystickButton* operator_Xbox_LeftBumper;

    Joystick* driverJoystick;
    JoystickButton* driver_Xbox_RB;
    JoystickButton* driver_Xbox_LB;
    JoystickButton* driver_Xbox_X;
    JoystickButton* driver_Xbox_B;

    Joystick* arduino1;
    Joystick* arduino2;
    JoystickButton* arduino_1;
    JoystickButton* arduino_2;
    JoystickButton* arduino_3;
    JoystickButton* arduino_4;
    JoystickButton* arduino_5;
    JoystickButton* arduino_6;
    JoystickButton* arduino_7;
    JoystickButton* arduino_8;
    JoystickButton* arduino_9;
    JoystickButton* arduino_10;
    JoystickButton* arduino_11;
    JoystickButton* arduino_12;
    JoystickButton* arduino_13;
    JoystickButton* arduino_14;
    JoystickButton* arduino_15;
    JoystickButton* arduino_16;
    JoystickButton* arduino_fire;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


public:
    OI();

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
    Joystick* getDriverJoystick();
    Joystick* getOperatorJoystick();
    double getOperatorTurnTable();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
    Joystick* getArduino1();
    Joystick* getArduino2();
    int getMatrixNumber();
    int getAutoMode();
    void debugArduino();
};
#endif
