// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "DepositBall.h"
DepositBall::DepositBall() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::ballCollector);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void DepositBall::Initialize() {
	Robot::ballCollector->setRollerOutput(-1);
}
// Called repeatedly when this Command is scheduled to run
void DepositBall::Execute() {

}
// Make this return true when this Command no longer needs to run execute()
bool DepositBall::IsFinished() {
	/*if(Robot::oi->getArduino2()->GetRawButton(1)) // pressed
	{
		return false;
	}
	else 
		return true;*/
    return false;
}
// Called once after isFinished returns true
void DepositBall::End() {
	Robot::ballCollector->setRollerOutput(0);
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DepositBall::Interrupted() {
	End();
}
