// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "TurretLoadLeft.h"
#include <math.h>
namespace
{
    const double c_timoutSeconds = 1.5; //PID stops after this time
    
    //Turret Parameters
    const double c_positionTurret = 0; //degrees
    const double c_setpointTurretTolerance = 0.1; // volts
    
}
TurretLoadLeft::TurretLoadLeft() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::turretWithPID);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void TurretLoadLeft::Initialize() {
    Robot::turretWithPID->setAbsoluteAngle(c_positionTurret);
    SetTimeout(c_timoutSeconds);	
}
// Called repeatedly when this Command is scheduled to run
void TurretLoadLeft::Execute() {
//    std::cout << "  Turret PID: Actual Volts: " << Robot::turretWithPID->turretAngleSensor->GetAverageVoltage() 
//            << ", Set Volts:" << Robot::turretWithPID->GetSetpoint() << ", Output: " << Robot::turretWithPID->getPIDOutput() << std::endl;
	
}
// Make this return true when this Command no longer needs to run execute()
bool TurretLoadLeft::IsFinished() {
    bool withinTurretError = (fabs(Robot::turretWithPID->ReturnPIDInput() - Robot::turretWithPID->convertAngleToVolts(c_positionTurret, false)) < c_setpointTurretTolerance);
    bool jsMovement = (fabs(Robot::oi->getOperatorJoystick()->GetRawAxis(c_turretRotate)) > 0.5);
    if(withinTurretError || jsMovement || IsTimedOut())
    {
        return true;
    }
    else
    {
        return false;
    }
}
// Called once after isFinished returns true
void TurretLoadLeft::End() {
    //Stop trying to set the position once we've reached it.
//    std::cout << "     TurretLoadLeft::End() - Disabling Turret PID" << std::endl;
    Robot::turretWithPID->Disable();
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void TurretLoadLeft::Interrupted() {
    End();
}
