// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "WinchPin.h"
WinchPin::WinchPin(bool setpin){
	Requires(Robot::ballCollector);
	m_setpin = setpin;
	
}
WinchPin::WinchPin() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooter);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	
	m_setpin = true;
}
// Called just before this Command runs the first time
void WinchPin::Initialize() {
	Robot::shooter->SetWinchPin(m_setpin);
//	std::cout << "WinchPin is being set to " << (m_setpin ? "true" : "false") << std::endl;
	SetTimeout(.25); //Time it takes to actuate the pin
}
// Called repeatedly when this Command is scheduled to run
void WinchPin::Execute() {
	
}
// Make this return true when this Command no longer needs to run execute()
bool WinchPin::IsFinished() {
	if(IsTimedOut()){
		return true;
	}
	else
	{
		return false;
	}
}
// Called once after isFinished returns true
void WinchPin::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void WinchPin::Interrupted() {
}
