// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef BALLCOLLECTOR_H
#define BALLCOLLECTOR_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
/**
 *
 *
 * @author ExampleAuthor
 */
class BallCollector: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SpeedController* rollerMotor;
	DigitalInput* catchBallSensor;
	DigitalInput* groundBallSensor;
	Solenoid* sensorPower;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	BallCollector();
	void InitDefaultCommand();
	void setRollerOutput(float output);
	void setSensorPower(bool on);
	bool isGroundBallSensorTripped();
	bool isCatchBallSensorTripped();
	void runWatchForBall();
};
#endif
