// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "CompressorSubSystem.h"
#include "../Robotmap.h"
CompressorSubSystem::CompressorSubSystem() : Subsystem("CompressorSubSystem") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	compressor = RobotMap::compressorSubSystemCompressor;
	tankPressure = RobotMap::compressorSubSystemTankPressure;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void CompressorSubSystem::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
void CompressorSubSystem::startCompressor()
{
    compressor->Start();
}
void CompressorSubSystem::stopCompressor()
{
    compressor->Stop();
}
bool CompressorSubSystem::isEnabled()
{
    return compressor->Enabled();
}
float CompressorSubSystem::getTankPSI()
{
    float volts = tankPressure->GetVoltage();
    //TODO: Update this formula for the real sensor
    float psi = (150/4.0) * (volts-.5); //(150psi/4.0V) * volts
    return volts;
}
