#ifndef DRIVEWITHPID_H
#define DRIVEWITHPID_H
#include "Commands/PIDSubsystem.h"
#include "WPILib.h"

class DriveWithPID: public PIDSubsystem {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Encoder* driveEncoder;
	SpeedController* leftFront;
	SpeedController* rightFront;
	RobotDrive* tankDrive2Motor;
	Solenoid* driveShift;
	SpeedController* leftDrive3;
	SpeedController* rightDrive3;
	Solenoid* dropDownCaster;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	DriveWithPID();
	double ReturnPIDInput();
	void UsePIDOutput(double output);
	void InitDefaultCommand();

	void setDriveOutputPID();
	void setDistance(double feet);
	void shiftGear(bool toLow);
	void toggleDropDown(bool toDrop);
	bool currentlyInLowGear(){return m_currentlyInLow;};
	bool currentlyDroppedDown(){return m_currentlyDroppedDown;};
	void setMotorOutput(float output);
	double getPIDOutput();
	void setArcadeOutput(float left, float right);
	void setTankOutput(float left, float right);


private:
	double m_feetToDrive;
	double m_distanceDriven;
	bool m_currentlyInLow;
	bool m_currentlyDroppedDown;
};
#endif
