#include "Shooter.h"
#include "../Robotmap.h"
#include "../Commands/WinchByJoystick.h"
Shooter::Shooter() : Subsystem("Shooter") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	winchMotor = RobotMap::shooterWinchMotor;
	brandingIronSensor = RobotMap::shooterBrandingIronSensor;
	winchPin = RobotMap::shooterWinchPin;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SetWinchPin(c_setPin);
}
    
void Shooter::InitDefaultCommand() {
	
}
void Shooter::SetMotorOutput(float output){
	winchMotor->Set(-output);
}
void Shooter::SetWinchPin(bool output){
    //std::cout << "SetWinchPin: " << output << std::endl;
	winchPin->Set(output);
    m_winchPin = output;
}
bool Shooter::GetWinchPin(){
    return m_winchPin;
}
void Shooter::SetFireCommand(int firePosition)
{
	m_globalFireCommand = firePosition;
}
int Shooter::GetFireCommand()
{
	return m_globalFireCommand;
}
