#ifndef SHOOTER_H
#define SHOOTER_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
/**
 *
 *
 * @author ExampleAuthor
 */
class Shooter: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SpeedController* winchMotor;
	DigitalInput* brandingIronSensor;
	Solenoid* winchPin;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Shooter();
	void InitDefaultCommand();
	void SetMotorOutput(float output);
	void SetWinchPin(bool output);
	bool GetWinchPin();
	void SetFireCommand(int firePosition);
	int GetFireCommand();
	
private:
	bool m_winchPin;
	int m_globalFireCommand;
};
#endif
